spring.application.name=movie-theater

server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/cinema_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Pa$$Na$$aIW0rd}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

docker.host=${DOCKER_HOST:npipe:////./pipe/docker_engine}

application.security.jwt.secret-key=${JWT_SECRET_KEY:7zX9pQ2vN8wR4yL6mK3jH1bG5tU8cW0eA3fD7gJ9kL2nQ}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo=DEBUG