spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=postgres
spring.datasource.password=Pa$$Na$$aIW0rd
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false